"""User-supplied discovery locations. Inclusion is not a legitimacy endorsement."""

CATALOG = [
    (
        "ClassAction.org investigations",
        "https://www.classaction.org/list-of-lawsuits",
        "settlements",
        "directory",
    ),
    ("ClassAction.org settlements", "https://www.classaction.org/settlements", "settlements", "directory"),
    ("Top Class Actions", "https://topclassactions.com/", "settlements", "directory"),
    ("OpenClassActions.com", "https://openclassactions.com/settlements.php", "settlements", "directory"),
    ("OpenClassActions.org", "https://openclassactions.org/", "settlements", "directory"),
    ("Claim Depot", "https://www.claimdepot.com/", "settlements", "directory"),
    ("Consumer Action", "https://consumer-action.org/", "settlements", "directory"),
    ("Kroll", "https://www.kroll.com/en", "settlements", "administrator"),
    ("Epiq", "https://www.epiqglobal.com/en-us", "settlements", "administrator"),
    ("JND", "https://jndla.com/", "settlements", "administrator"),
    ("Angeion Group", "https://angeiongroup.com/", "settlements", "administrator"),
    ("Simpluris case search", "https://simpluris.com/case-search", "settlements", "administrator"),
    ("Verita", "https://veritaglobal.com/", "settlements", "administrator"),
    ("Rust Consulting", "https://rustconsulting.com/", "settlements", "administrator"),
    ("AB Data Class Action", "https://abdataclassaction.com/", "settlements", "administrator"),
    ("Atticus Administration", "https://atticusadmin.com/", "settlements", "administrator"),
    ("Privacy Rights Clearinghouse", "https://privacyrights.org/", "breach_announcements", "breach_notice"),
    ("DataBreaches.net", "https://databreaches.net/", "breach_announcements", "breach_notice"),
    (
        "Have I Been Pwned public announcements",
        "https://haveibeenpwned.com/",
        "breach_announcements",
        "breach_notice",
    ),
    ("Maine Attorney General", "https://maine.gov/ag", "breach_announcements", "government"),
    ("Massachusetts government", "https://mass.gov/", "breach_announcements", "government"),
    ("New York Attorney General", "https://ag.ny.gov/", "breach_announcements", "government"),
    ("SEC", "https://www.sec.gov/", "government_refunds", "government"),
    ("CFPB", "https://www.consumerfinance.gov/", "government_refunds", "government"),
    ("FTC refunds", "https://www.ftc.gov/enforcement/refunds", "government_refunds", "government"),
    ("Department of Justice", "https://justice.gov/", "government_refunds", "government"),
    ("Analytics Consulting", "https://www.analyticsllc.com/", "settlements", "administrator"),
    ("Strategic Claims Services", "https://strategicclaims.net/", "settlements", "administrator"),
]
