"""add case deduplication and evidence references"""

from alembic import op
import sqlalchemy as sa

revision = "109677d1de04"
down_revision = "622b46e54330"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence",
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("opportunity_id", sa.String(length=36), nullable=False),
        sa.Column("reference", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("opportunities") as batch:
        batch.add_column(sa.Column("case_key", sa.String(length=200), nullable=True))
        batch.create_unique_constraint("uq_opportunities_case_key", ["case_key"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("opportunities") as batch:
        batch.drop_constraint("uq_opportunities_case_key", type_="unique")
        batch.drop_column("case_key")
    op.drop_table("evidence")
    # ### end Alembic commands ###
