"""Retain discovery streams and breach announcements"""

from alembic import op
import sqlalchemy as sa

revision = "d8a0b38d9584"
down_revision = "109677d1de04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discovery_observations",
        sa.Column("opportunity_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("changed_fields", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("opportunities", sa.Column("defendant", sa.String(length=300), nullable=True))
    op.add_column(
        "opportunities",
        sa.Column("record_type", sa.String(length=40), server_default="unknown", nullable=False),
    )
    op.add_column(
        "opportunities",
        sa.Column("program_type", sa.String(length=40), server_default="settlements", nullable=False),
    )
    op.add_column("opportunities", sa.Column("official_notice_url", sa.Text(), nullable=True))
    op.add_column("opportunities", sa.Column("claim_opens_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("opportunities", sa.Column("eligibility_start", sa.Date(), nullable=True))
    op.add_column("opportunities", sa.Column("eligibility_end", sa.Date(), nullable=True))
    op.add_column("opportunities", sa.Column("documentation_requirements", sa.Text(), nullable=True))
    op.add_column("opportunities", sa.Column("payment_timeline", sa.Text(), nullable=True))
    op.add_column(
        "opportunities", sa.Column("possible_duplicate_ids", sa.JSON(), server_default="[]", nullable=False)
    )
    op.add_column("opportunities", sa.Column("duplicate_review_notes", sa.Text(), nullable=True))
    op.add_column(
        "sources", sa.Column("stream", sa.String(length=40), server_default="settlements", nullable=False)
    )
    op.add_column(
        "sources", sa.Column("source_role", sa.String(length=40), server_default="directory", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sources", "source_role")
    op.drop_column("sources", "stream")
    op.drop_column("opportunities", "duplicate_review_notes")
    op.drop_column("opportunities", "possible_duplicate_ids")
    op.drop_column("opportunities", "payment_timeline")
    op.drop_column("opportunities", "documentation_requirements")
    op.drop_column("opportunities", "eligibility_end")
    op.drop_column("opportunities", "eligibility_start")
    op.drop_column("opportunities", "claim_opens_at")
    op.drop_column("opportunities", "official_notice_url")
    op.drop_column("opportunities", "program_type")
    op.drop_column("opportunities", "record_type")
    op.drop_column("opportunities", "defendant")
    op.drop_table("discovery_observations")
    # ### end Alembic commands ###
